### PR TITLE
Fix the way BlendMode is specified when dealing with transparent images

### LINKED ISSUE #7: Transparent PNGs become completely black when converted to JPEG
Happens with e.g. this image: https://s3.amazonaws.com/creation.howrse.com/100245550-normal.png

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #7 

Took me over one hour of debugging until I figured this out :smile:

### CODE REVIEW

**Comment by bonzai** [comment]
Thanks!

Can you revert the following commits:

- Ignore PhpStorm project files, at least for now
- Add some phpdoc type-hints to InsertCommand (= remove `/* @var */` comments)

**Comment by Jalle19** [comment]
Why would you not want type-hints? I guess I could indicate the return type in the methods instead of using inline vars.

**Comment by Jalle19** [comment]
Actually `getCore()` comes from Intervention itself so I can't change that. I'll drop the commits.

**Comment by Jalle19** [comment]
Updated

**Pull request merged**
